### Crear una venta
POST http://localhost:3000/ventas/crear
Content-Type: application/json

{
  "total": 10000,
  "id_usuario": 16
}

### Listar todas las ventas
GET http://localhost:3000/ventas/listar

### Obtener una venta por ID
GET http://localhost:3000/ventas/4

### Actualizar una venta
PATCH http://localhost:3000/ventas/4
Content-Type: application/json

{
  "total": 50000
}

### Eliminar una venta
DELETE http://localhost:3000/ventas/4
