# Obtener todos los pasajeros
GET http://localhost:3000/passengers

# Buscar pasajero por ID
GET http://localhost:3000/passengers/1

# Crear pasajero
POST http://localhost:3000/passengers
Content-Type: application/json

{
  "name": "Laura Martínez",
  "age": 28,
  "ticketNumber": "T789"
}

# Crear varios pasajeros (bulk)
POST http://localhost:3000/passengers/bulk
Content-Type: application/json

[
  { "name": "Pedro Ruiz", "age": 40, "ticketNumber": "T999" },
  { "name": "María López", "age": 22, "ticketNumber": "T888" }
]

# Actualizar pasajero completo (PUT)
PUT http://localhost:3000/passengers/1
Content-Type: application/json

{
  "name": "Carlos Pérez",
  "age": -26,
  "ticketNumber": "T555"
}

# Actualizar ticket de un pasajero
PUT http://localhost:3000/passengers/2/ticket
Content-Type: application/json

{
  "ticketNumber": "T777"
}

# Actualizar solo edad
PATCH http://localhost:3000/passengers/1/edad
Content-Type: application/json

{
  "edad": 35
}

# Actualizar solo nombre
PATCH http://localhost:3000/passengers/2/nombre
Content-Type: application/json

{
  "nombre": "Andrea Torres"
}
