# Obtener todas las rutas
GET http://localhost:3000/routes

# Obtener ruta por ID
GET http://localhost:3000/routes/1

# Crear nueva ruta
POST http://localhost:3000/routes
Content-Type: application/json

{
  "origen": "Barranquilla",
  "destino": "Santa Marta"
}

# Crear varias rutas (bulk)
POST http://localhost:3000/routes/bulk
Content-Type: application/json

[
  { "origen": "Pasto", "destino": "Popayán" },
  { "origen": "Manizales", "destino": "Armenia" }
]
