### Crear usuario
POST http://localhost:3000/usuario/register
Content-Type: application/json

{
  "nombre": "terry",
  "correo": "terry@mail.com",
  "contrasena": "terry123478",
  "rol": "admin"
}

### Listar usuarios
GET http://localhost:3000/usuario/list

### Obtener usuario por id
GET http://localhost:3000/usuario/12

### Actualizar usuario (cambiar nombre)
PATCH http://localhost:3000/usuario/12
Content-Type: application/json

{
  "nombre": "terrymoto"
}

### Borrar usuario
DELETE http://localhost:3000/usuario/12
